-- Safe investment_tiers table creation
-- Handles missing functions and existing tables gracefully

-- First create the handle_updated_at function if it doesn't exist
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create investment_tiers table with proper error handling
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'investment_tiers') THEN
        
        CREATE TABLE public.investment_tiers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL UNIQUE,
            description TEXT,
            min_amount DECIMAL(20,8) NOT NULL DEFAULT 0,
            max_amount DECIMAL(20,8), -- NULL means unlimited
            investment_period_days INTEGER NOT NULL DEFAULT 30,
            daily_roi DECIMAL(10,8) NOT NULL DEFAULT 0.005, -- Daily ROI as decimal (0.005 = 0.5%)
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_active BOOLEAN NOT NULL DEFAULT true,
            features JSONB, -- Array of features for this tier
            allocation_mix JSONB, -- Asset allocation percentages (e.g., {"BTC": 40, "ETH": 30, "USDT": 30})
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Create indexes
        CREATE INDEX idx_investment_tiers_active_sort ON public.investment_tiers(is_active, sort_order);
        CREATE INDEX idx_investment_tiers_min_amount ON public.investment_tiers(min_amount);
        
        RAISE NOTICE 'investment_tiers table created successfully';
        
    ELSE
        -- Table exists, add missing columns if needed
        RAISE NOTICE 'investment_tiers table already exists, checking for missing columns...';
        
        BEGIN
            ALTER TABLE public.investment_tiers ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.investment_tiers ADD COLUMN IF NOT EXISTS features JSONB;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.investment_tiers ADD COLUMN IF NOT EXISTS allocation_mix JSONB;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        RAISE NOTICE 'Missing columns added to existing investment_tiers table';
    END IF;
END $$;

-- Insert default tier data (only if table is empty)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'investment_tiers') THEN
        -- Check if table has data
        IF NOT EXISTS (SELECT 1 FROM public.investment_tiers LIMIT 1) THEN
            
            INSERT INTO public.investment_tiers (name, description, min_amount, max_amount, investment_period_days, daily_roi, sort_order, features, allocation_mix) VALUES
            (
                'Tier 1',
                'Entry-level investment tier with competitive returns.',
                150.00,
                1000.00,
                3,
                0.1, -- 10% daily (30% total over 3 days)
                1,
                '["Basic trading signals", "Email support", "Daily ROI payouts"]',
                '{"BTC": 40, "ETH": 30, "USDT": 30}'
            ),
            (
                'Tier 2',
                'Intermediate tier with enhanced returns and features.',
                1000.01,
                10000.00,
                7,
                0.0643, -- 6.43% daily (45% total over 7 days)
                2,
                '["Advanced trading signals", "Priority support", "Daily ROI payouts", "Portfolio analytics"]',
                '{"BTC": 35, "ETH": 35, "USDT": 30}'
            ),
            (
                'Tier 3',
                'Advanced tier for serious investors.',
                10000.01,
                20000.00,
                14,
                0.0357, -- 3.57% daily (50% total over 14 days)
                3,
                '["Premium trading signals", "24/7 support", "Daily ROI payouts", "Advanced analytics", "Risk management tools"]',
                '{"BTC": 30, "ETH": 40, "USDT": 30}'
            ),
            (
                'Tier 4',
                'Professional tier with high returns.',
                20000.01,
                50000.00,
                30,
                0.0333, -- 3.33% daily (100% total over 30 days)
                4,
                '["VIP trading signals", "Dedicated account manager", "Daily ROI payouts", "Custom analytics", "API access", "Lower fees"]',
                '{"BTC": 25, "ETH": 45, "USDT": 30}'
            ),
            (
                'Tier 5',
                'Elite tier for maximum returns and exclusive benefits.',
                50000.01,
                10000000.00,
                60,
                0.0333, -- 3.33% daily (200% total over 60 days)
                5,
                '["Exclusive signals", "Personal advisor", "Daily ROI payouts", "Custom strategies", "Priority API", "Zero fees", "Exclusive events"]',
                '{"BTC": 20, "ETH": 50, "USDT": 30}'
            )
            ON CONFLICT (name) DO NOTHING;
            
            RAISE NOTICE 'Default investment tiers inserted successfully';
        ELSE
            RAISE NOTICE 'investment_tiers table already has data, skipping insert';
        END IF;
    END IF;
END $$;

-- Create trigger (drop if exists first)
DROP TRIGGER IF EXISTS handle_investment_tiers_updated_at ON public.investment_tiers;
CREATE TRIGGER handle_investment_tiers_updated_at
    BEFORE UPDATE ON public.investment_tiers
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investment_tiers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investment_tiers TO service_role;

-- Verify table creation and show data
SELECT 
    'investment_tiers' as table_name,
    'TABLE' as object_type,
    'CREATED/UPDATED' as status,
    NOW() as created_at;

SELECT 
    '=== INVESTMENT TIERS DATA ===' as section,
    id,
    name,
    min_amount,
    max_amount,
    daily_roi,
    investment_period_days,
    sort_order,
    is_active
FROM public.investment_tiers
ORDER BY sort_order;
