-- Create user_positions table safely
-- Handles existing tables gracefully

-- First create handle_updated_at function if it doesn't exist
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create user_positions table with proper error handling
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'user_positions') THEN
        
        CREATE TABLE public.user_positions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
            tier_id BIGINT NOT NULL REFERENCES public.investment_tiers(id) ON DELETE RESTRICT,
            amount DECIMAL(20,8) NOT NULL DEFAULT 0,
            currency VARCHAR(10) NOT NULL DEFAULT 'USDT',
            status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'matured', 'closed')),
            opened_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            matures_at TIMESTAMP WITH TIME ZONE,
            closed_at TIMESTAMP WITH TIME ZONE,
            
            -- Trading position details
            symbol VARCHAR(20),
            position_type VARCHAR(10) CHECK (position_type IN ('long', 'short')),
            entry_price DECIMAL(20,8),
            current_price DECIMAL(20,8),
            quantity DECIMAL(20,8),
            unrealized_pnl DECIMAL(20,8) DEFAULT 0,
            
            -- ROI tracking
            accrued_roi DECIMAL(20,8) DEFAULT 0,
            last_roi_calculation TIMESTAMP WITH TIME ZONE,
            
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Create indexes for performance
        CREATE INDEX idx_user_positions_user_id ON public.user_positions(user_id);
        CREATE INDEX idx_user_positions_tier_id ON public.user_positions(tier_id);
        CREATE INDEX idx_user_positions_status ON public.user_positions(status);
        CREATE INDEX idx_user_positions_matures_at ON public.user_positions(matures_at);
        CREATE INDEX idx_user_positions_user_status ON public.user_positions(user_id, status);
        
        RAISE NOTICE 'user_positions table created successfully';
        
    ELSE
        -- Table exists, add missing columns if needed
        RAISE NOTICE 'user_positions table already exists, checking for missing columns...';
        
        -- Add missing columns one by one
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS tier_id BIGINT NOT NULL REFERENCES public.investment_tiers(id) ON DELETE RESTRICT;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS amount DECIMAL(20,8) NOT NULL DEFAULT 0;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS currency VARCHAR(10) NOT NULL DEFAULT 'USDT';
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS opened_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS matures_at TIMESTAMP WITH TIME ZONE;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP WITH TIME ZONE;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS symbol VARCHAR(20);
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS position_type VARCHAR(10);
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS entry_price DECIMAL(20,8);
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS current_price DECIMAL(20,8);
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS quantity DECIMAL(20,8);
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS unrealized_pnl DECIMAL(20,8) DEFAULT 0;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS accrued_roi DECIMAL(20,8) DEFAULT 0;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS last_roi_calculation TIMESTAMP WITH TIME ZONE;
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        BEGIN
            ALTER TABLE public.user_positions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
        EXCEPTION WHEN duplicate_column THEN NULL; END;
        
        RAISE NOTICE 'Missing columns added to existing user_positions table';
    END IF;
END $$;

-- Create indexes if they don't exist
DO $$
BEGIN
    BEGIN
        CREATE INDEX idx_user_positions_user_id ON public.user_positions(user_id);
        RAISE NOTICE 'Created user_id index';
    EXCEPTION WHEN duplicate_table THEN 
        RAISE NOTICE 'user_id index already exists';
    END;
    
    BEGIN
        CREATE INDEX idx_user_positions_tier_id ON public.user_positions(tier_id);
        RAISE NOTICE 'Created tier_id index';
    EXCEPTION WHEN duplicate_table THEN 
        RAISE NOTICE 'tier_id index already exists';
    END;
    
    BEGIN
        CREATE INDEX idx_user_positions_status ON public.user_positions(status);
        RAISE NOTICE 'Created status index';
    EXCEPTION WHEN duplicate_table THEN 
        RAISE NOTICE 'status index already exists';
    END;
    
    BEGIN
        CREATE INDEX idx_user_positions_matures_at ON public.user_positions(matures_at);
        RAISE NOTICE 'Created matures_at index';
    EXCEPTION WHEN duplicate_table THEN 
        RAISE NOTICE 'matures_at index already exists';
    END;
    
    BEGIN
        CREATE INDEX idx_user_positions_user_status ON public.user_positions(user_id, status);
        RAISE NOTICE 'Created user_status index';
    EXCEPTION WHEN duplicate_table THEN 
        RAISE NOTICE 'user_status index already exists';
    END;
END $$;

-- Create trigger (drop if exists first)
DROP TRIGGER IF EXISTS handle_user_positions_updated_at ON public.user_positions;
CREATE TRIGGER handle_user_positions_updated_at
    BEFORE UPDATE ON public.user_positions
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Enable Row Level Security
ALTER TABLE public.user_positions ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
CREATE POLICY "Users can view own positions" ON public.user_positions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own positions" ON public.user_positions
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Service role full access" ON public.user_positions
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_positions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_positions TO service_role;

-- Verify table creation
SELECT 
    'user_positions' as table_name,
    'TABLE' as object_type,
    'CREATED/UPDATED' as status,
    NOW() as created_at;
