-- Create investment_strategies table
-- This table defines the different investment strategies available in the platform

CREATE TABLE IF NOT EXISTS public.investment_strategies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    asset_class VARCHAR(100) NOT NULL, -- New field for asset class categorization
    min_amount DECIMAL(20,8) NOT NULL DEFAULT 0,
    max_amount DECIMAL(20,8), -- NULL means unlimited
    investment_period_days INTEGER NOT NULL DEFAULT 30,
    daily_roi DECIMAL(10,8) NOT NULL DEFAULT 0.005, -- Daily ROI as decimal (0.005 = 0.5%)
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    features JSONB, -- Array of features for this strategy
    allocation_mix JSONB, -- Asset allocation percentages (e.g., {"BTC": 40, "ETH": 30, "USDT": 30})
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_investment_strategies_active_sort ON public.investment_strategies(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_investment_strategies_min_amount ON public.investment_strategies(min_amount);
CREATE INDEX IF NOT EXISTS idx_investment_strategies_asset_class ON public.investment_strategies(asset_class);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION public.handle_strategies_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_investment_strategies_updated_at
    BEFORE UPDATE ON public.investment_strategies
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_strategies_updated_at();

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investment_strategies TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investment_strategies TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.investment_strategies_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.investment_strategies_id_seq TO service_role;
